[package]
name = "rust_game"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.29"
glow = "0.13"
sdl2 = { version = "0.35", features = ["static-link"] }
rand = "0.8.3"
serde = { version = "1.0", features = ["derive"] }
glutin = "0.31"